---
ID: "068b57ac-22ca-4d10-8553-5d52a0ef5858"
Parent: "386af4ae-8558-4185-ac37-f57e776915a9"
Template: "386af4ae-8558-4185-ac37-f57e776915a9"
Path: /sitecore/templates/Feature/PageContent/FieldSample/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220928T130353Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
