---
ID: "e8719ca5-2164-46c0-91c1-b6881329b7ab"
Parent: "3f8a6a5d-7b1a-4566-8cd4-0a50f3030bd8"
Template: "3f8a6a5d-7b1a-4566-8cd4-0a50f3030bd8"
Path: /sitecore/templates/Foundation/Content/Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{3F8A6A5D-7B1A-4566-8CD4-0A50F3030BD8}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0a209e70-fbb1-4a7a-b468-56f47e2176dc"
      Hint: BrowserTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160628T133845Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
