---
ID: "431a4468-4049-4d7d-89c3-3b1fa98f00db"
Parent: "94382bcf-c3f2-4a11-8bbe-9e3f84e34b84"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/Project/RainflyTraining/ProductPage
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220801T132527Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
